#!/bin/bash

CONSUL_HOST=${CONSUL_HOST:-172.17.0.1}

exec /bin/consul-template \
    -consul ${CONSUL_HOST}:8500 \
    -wait=5s \
    -template "/etc/nginx/templates/default.conf.ctmpl:/etc/nginx/conf.d/default.conf:/usr/sbin/nginx -s reload"
